name: 'Deployment'

on:
  push:
    branches:
      - master
      - main
      - '*'
      - '**'

jobs:

  run-test:
    name: Testing Stage success
    uses: ./.github/workflows/test.yaml

  build-app-image:
    name: Build docker and push to ECR
    uses: ./.github/workflows/build.yaml

  slack-notify:
    name: Deploy to EKS
    needs: [run-test, build-app-image]
    if: always()
    uses: ./.github/workflows/slack.yaml
    with:
      STATUS: "${{ needs.run-test.result }} ${{ needs.build-app-image.result }}"
    secrets:
      SLACK_PR_CHANNEL_ID: ${{ secrets.SLACK_PR_CHANNEL_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}